title: Karem SAAD  # You can add your name here

logo: cropped_circle_image.png # Use a relative path to logo image 

description: Dr. Eng. karem SAAD
Natural Resources/Remote Sensing/Environmental Specialist | 12+ yrs Exp | PhD | MEPI Alumni | USFS Expert | UN consultant

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
