title: Karem SAAD  # You can add your name here

logo: cropped_circle_image.png # Use a relative path to logo image 

description: Natural Resources & Environment Expert National Engineering School of Sfax (ENIS) University of Sfax

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
